const Router = require('express')
const router = new Router()
const professionRouter = require('./professionRouter')
const userRouter = require('./userRouter')
const postRouter = require('./postRouter')
const educationRouter = require('./educationRouter')
const workExperienceRouter = require('./workExperienceRouter')
const skillRouter = require('./skillRouter')
const cityRouter = require('./cityRouter')
const questionRouter = require('./questionRouter')
const answerVariantRouter = require('./answerVariantRouter')
const contactRouter = require('./contactRouter')
const messageRouter = require('./messageRouter')
const likeRouter = require('./likeRouter')
const universityRouter = require('./universityRouter')
const jobRouter = require('./jobRouter')
const resumeRouter = require('./resumeRouter')
const vacancyRouter = require('./vacancyRouter')
const resumeSkillsRouter = require('./resumeSkillsRouter')
const vacancySkillsRouter = require('./vacancySkillsRouter')
const testResultsRouter = require('./testResultsRouter')
const newMessagesRouter = require('./newMessageRouter')

router.use('/professions', professionRouter)
router.use('/users', userRouter)
router.use('/posts', postRouter)
router.use('/educations', educationRouter)
router.use('/work_experiences', workExperienceRouter)
router.use('/skills', skillRouter)
router.use('/cities', cityRouter)
router.use('/questions', questionRouter)
router.use('/answer_variants', answerVariantRouter)
router.use('/contacts', contactRouter)
router.use('/messages', messageRouter)
router.use('/likes', likeRouter)
router.use('/universities', universityRouter)
router.use('/jobs', jobRouter)
router.use('/resumes', resumeRouter)
router.use('/vacancies', vacancyRouter)
router.use('/resume_skills', resumeSkillsRouter)
router.use('/vacancy_skills', vacancySkillsRouter)
router.use('/test_results', testResultsRouter)
router.use('/new_messages', newMessagesRouter)


module.exports = router
